apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: telegram-to-kakfa
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: telegram-source
    properties:
      authorizationToken: <token-from-bot-father>
  steps:
  - ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: has-header-filter-action
    properties:
      name: "chat-id"
      #value: <your-chat-id (optional)>
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: kafka-sink
    properties:
      user: <service-account>
      password: <password>
      bootstrapServers: <server>
      topic: chatbot-x
